### ISSUE TITLE
Add new methods

### ISSUE THREAD

**Issue by clementallen** [clementallen/smithers#28]
## Overview
Add the following methods to the Smithers class along with unit tests and documentation:

- lastSuccessfulBuild (`/job/{name}/lastSuccessfulBuild/api/json`)
- lastStableBuild (`/job/{name}/lastStableBuild/api/json`)
- lastUnsuccessfulBuild (`/job/{name}/lastUnsuccessfulBuild/api/json`)
- specificBuild (`/job/{name}/{build}/api/json`)
- overallLoad (`/overallLoad/api/json`)
- queue (`/queue/api/json`)

## Technical details
- Follow the pattern of other methods by adding the method to the Smithers class using the `createPath` function to generate the api call path and the `this.caller.get` method for handling the request.

- Add unit tests for the method similar to existing tests

- Add documentation to the README

**Comment by andrey-semin** [comment]
Let me take it

**Comment by clementallen** [comment]
All yours @andrey-semin - thanks! :)

**Comment by clementallen** [comment]
Closed in #29
